# Generated by Django 5.0.4 on 2024-04-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=256)),
                ('fullname', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
    ]
