# Generated by Django 5.0.4 on 2024-05-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='vendor',
            new_name='vendor_id',
        ),
    ]
