###
POST http://localhost:8000/api/user
Content-Type: application/json

{
    "username": "John11111",
    "password": "1234asdF!",
    "confirm_password": "1234asdF!",
    "fullname": "Test Test",
    "number": "+38344000000",
    "email": "tes22t112@gmail.com"
}

###
GET http://localhost:8000/api/user?username=test123&password=Password123!
Content-Type: application/json
###
PUT http://localhost:8000/api/user
Content-Type: application/json

{
    "guid": "caabe8c9-c8cd-45ab-a10c-41fa49212837",
    "username": "UpdatedName",
    "number": "+38349123456",
    "role": "admin",
    "email": "updatedemail@example.com",
    "password": "NewPassword123!",
    "confirm_password": "NewPassword123!"
}
### update using only password
PUT http://localhost:8000/api/user
Content-Type: application/json

{
    "guid": "caabe8c9-c8cd-45ab-a10c-41fa49212837",
    "password": "NewPassword1234!",
    "confirm_password": "NewPassword1234!"
}
###
POST http://localhost:8000/api/ticket
Content-Type: application/json

{
  "from_location": "City A",
  "to_location": "City B",
  "start_time": "2024-05-30T12:00:00Z",
  "end_time": "2024-05-30T14:00:00Z",
  "price": "100.00",
  "type": "economy",
  "seat": "12A",
  "vendor_id": 1
}
###
GET http://localhost:8000/api/ticket?id=11
Content-Type: application/json

###

GET http://localhost:8000/api/booking?id=11
Content-Type: application/json

###
POST http://localhost:8000/api/vendor
Content-Type: application/json

{
  "vendor_name": "New Vendor"
}
###
GET http://localhost:8000/api/vendor?id=1
Content-Type: application/json

###
GET http://localhost:8000/api/transaction?id=1
Content-Type: application/json


###
GET http://localhost:8000/api/payment?id=1
Content-Type: application/json


###
POST http://localhost:8000/api/change_password?username=John212&password=1234asdF!&new_password=Password123!
Content-Type: application/json